### PR TITLE
Very big wiki update :)

### PR DESCRIPTION
**Pull request by ravenbuilder934**
I updated all the item and block pages, deleted the Field page (since we have Farm & Field now), and combined the Supply Camp and Supply Ship pages. I also deleted the Decoblocks folder (since all the things in it are shown under Items in the header) and moved everything in it to the Items folder.

I also updated the Stone Smeltery, Smeltery, University, Warehouse, Dyer's Hut, Fletcher's Hut, Glassblower's Hut, Mechanic's Hut, Plantation, School, Tavern, Builder's Hut, and Stonemason's Hut pages, plus made minor changes to the Hospital page.

I also (hopefully) fixed the link on the 404 page to go to the homepage, changed the copyright on the footer from 2019 to 2020, and fixed the link to the curseforge download on the Java installation page.

And turned the Knight and Ranger pages into Knight in Training and Ranger in Training pages, as well as updated the GUI page to reflect changes made in ldtteam/minecolonies#5067. I also updated the recipes page and added new recipes to it, and moved the Troubleshooting page from the Troubleshooting folder, where it was the only thing, to the misc folder (which is what it's shown under in the header).

(Combined #340, #342, #347, and #350, then added more commits)

105 commits! Wow!

### CODE REVIEW

**Comment by lunadragnstar** [comment]
I'm waiting until the wiki is fixed before merging any more updates.

**Comment by ravenbuilder934** [comment]
@lunadragnstar What do you mean 'fixed'?

**Comment by lunadragnstar** [comment]
the actual wiki is down, the only way to access it is through the github site

**Comment by ravenbuilder934** [comment]
Why are you waiting until it's fixed? I think #333 was merged when it was down...

**Pull request merged**
