### PR TITLE
Update schematics.md

### PR DESCRIPTION
**Pull request by Moobien**
Closes #

## Changes proposed:
- 
-

### CODE REVIEW

**Comment by MotionlessTrain** [comment]
Did you add this to the wrong list?
Now it looks like that you are supposed to rename files

**Comment by Moobien** [comment]
It should be in the do not section

**Comment by MotionlessTrain** [comment]
That is what I thought. But you added it in the "Do" list

**Comment by Moobien** [comment]
I thought it put it there. Are you able to correct it?

**Comment by MotionlessTrain** [comment]
I don't think I can change someone else's pull request, and I'm not at my computer right now to open another one

**Pull request closed without merging**
