### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by AlmightyAnubis**
Closes #

## Changes proposed:
- Extend worker classification in Resource Gatherer and Crafter to improve clarity

Merge please :D

### CODE REVIEW

**Comment by MotionlessTrain** [comment]
Some workers are both: e.g. the farmer can craft a few items as well (seeds, melons, haybales), and the forester strips logs on request

**Comment by Thodor12** [comment]
This type was initially made to just be able to distinquish between workers and guards, this was done for a specific guard overhaul, not to further separate citizens into roles.
As MotionlessTrain said a lot of workers have multiple roles and wouldn't be able to be classified under a certain role.

**Comment by Thodor12** [comment]
If we want to do this you have to consider making the type an array, which mean the worker could fall under multiple sublists.
But I want @anonymous563 opinion on this if we want to do this or not.

**Comment by AlmightyAnubis** [comment]
Ok, I just wanted the classification in the drop down menu so you can find workers faster. A array would solve the issue of some workers being both, but it would make the drop down list longer and stuff harder to find. But I am not sure

**Comment by Thodor12** [comment]
Not necessarily, the idea of multiple roles would be that the worker would simply appear twice in the list under both categories.

We might have to do some research if we can add dropdowns in other dropdowns because the list is already very long.

**Comment by AlmightyAnubis** [comment]
Ok, I was afraid of the long list that would be created with listing them in 2 categories, but the dropdown-dropdown-version would be a nice idea.

**Comment by Talyda** [comment]
Why would you want to do that in the first place? I don't understand the reason for separating workers like that?

**Comment by MotionlessTrain** [comment]
^ Especially with the amount of workers that can do both, and the amount of workers that the mod already has, this list becomes probably too long

**Comment by Thodor12** [comment]
Currently the menu dropdowns already extends FAR beyond the rendered page itself in some cases.
All of the menus could be a lot shorter and we have to fix the background not rendering behind it too

**Comment by Talyda** [comment]
How could you make them shorter though? Unless you mean with like a scroll bar in the drop down?

**Comment by Thodor12** [comment]
I was thinking collapsible sections, so the current sub headers that it has would get a button inside them to reveal the content below them.

**Comment by Thodor12** [comment]
The main issue is just that bootstrap is so goddamn annoying to use you can't even make a submenu in the thing without having to work around it with a big jQuery block to handle the button clicks correctly.

**Comment by anonymous563** [comment]
> If we want to do this you have to consider making the type an array, which mean the worker could fall under multiple sublists. But I want @anonymous563 opinion on this if we want to do this or not.

I generally don't think links should be kept in two different places.

**Comment by anonymous563** [comment]
This is being added in #846

**Pull request closed without merging**
