### PR TITLE
Update placeholderblocks.md

### PR DESCRIPTION
**Pull request by Moobien**
corrected well out of date and incorrect information

Closes #

## Changes proposed:
- 
-

### CODE REVIEW

**Comment by Thodor12** [comment]
I'm redoing this entire page for the new wiki anyway

**Comment by Moobien** [comment]
> No I mean the literal entire page has already been reworked, including all text

is it live yet?

**Comment by Thodor12** [comment]
No, but I don't intend to update the wiki with all too much yet anymore since I've got to backport all of those changes to entirely new files

**Comment by Moobien** [comment]
so until your changes are live, you are happy to keep incorrect and out of date information on the wiki? I personally think this should be merged so at least the information is correct until Thodor's Wiki MkII goes online.

**Pull request merged**
