### PR TITLE
Update nethermine.md

### PR DESCRIPTION
**Pull request by Deepfriedsoldier**
Added a Note stating that this building is not yet available in all colony styles. This was a point of confusion for myself and others I have seen online and I feel is worth noting on the wiki. Obviously this can change in future so I added the version number as reference.

Closes #

## Changes proposed:
- 
-

### CODE REVIEW

**Comment by MotionlessTrain** [comment]
You can also click the hut block in the air in recent 1.19.2 versions, to give you a list which styles have a nether miner

**Comment by Deepfriedsoldier** [comment]
> You can also click the hut block in the air in recent 1.19.2 versions, to give you a list which styles have a nether miner

Very good to know! Thank you.

**Comment by anonymous563** [comment]
I don't think this is the right place for this information since this may apply to other buildings as well, as well as this info changing according to the builders' work.

**Comment by Deepfriedsoldier** [comment]
> I don't think this is the right place for this information since this may apply to other buildings as well, as well as this info changing according to the builders' work.

On the contrary I feel this is the best place so long as somebody edits it once the style is updated. Most people that have an issue with an item in the mod will likely first check the wiki page for that item. Very few people will want to look through the entire wiki to find an oddly placed snippet of information. I am not saying the way I worded it is the best way, but that is what this edit review system is for right? To tweak and fine tune the wiki to be most user friendly. 

You have to remember a wiki is not there for those that already know everything. Its there for those who wish to learn or have a problem.

**Comment by MotionlessTrain** [comment]
One of the issues is that it is not just one style that misses a nether mine, but a number of styles. It is not feasible to check whether all styles have one once any of those styles got one. They are maintained by different people, each having their own schedule.

And indeed, if the message is going to go on a building's page, it should go on all buildings' pages, since it may apply to all buildings.

My previous comment about checking which style(s) have a building was meant to be part of the message. It is more descriptive to explain where you can find styles that do have a nether mine, rather than just stating that not all of them have one.

**Comment by anonymous563** [comment]
I agree with Train's comment that if this goes on any building, it should go on all of them. However, putting it on all of them doesn't seem to make sense either; it's overly redundant. As such, I'd prefer putting it on some more centralized page, like the schematics tutorial or even the home page ("New styles for each building are always being added!" or some such).

**Comment by Thodor12** [comment]
I'm also going to agree with Train and anonymous, this information does not belong on the wiki since the wiki does not contain any information about style packs and such and the differences between them.

I think it's better if we close this considering that all main wiki contributors disagree with this, this is more like a support question as to why it's missing.

**Pull request closed without merging**
