### PR TITLE
Update stash.md

### PR DESCRIPTION
**Pull request by NeoSunSoar**
Add that the stash block can accept hoppers and be used to automate pick up of items created outside of the Minecolonies mod such as mob farms, vine farms, and with machines created in other mods such as Create or Immersive Engineering.  Many may not know that this block can be used in this way to automate and that this brings alot of cross compatibility between other mods and Minecolonies.

Closes #

## Changes proposed:
- To use the stash, right-click on it to bring up the inventory, which works like a chest. Put items in the stash and a Courier from the nearest Warehouse will pick them up.
- To use the stash, right-click on it to bring up the inventory, which works like a chest and can also accept hoppers for automation. Put items in the stash and a Courier from the nearest warehouse will pick them up and deposit them for workers or your own Requests. This allows for the creation of automated farms outside of Minecolonies and cross compatibility with other mods that automate through machinery giving your workers access to the materials they need for the recipes you teach them. 

Merge please :D

### CODE REVIEW

**Review by Thodor12 — CHANGES_REQUESTED** [review]
Personally I think the mention of being able to use with droppers is sufficient, if you start dropping in items en masse into the request system from a stash it will break the balance of the mod, not to mention this is going to fill your warehouses really fast.

If others feel like this is necessary, then fix the grammatical issues in the second sentence (no random uppercase words, "Worker" instead of "Worker's") also follow the guidelines of linking to buildings by using `{% include links/building.html key="warehouse" %}`

**Comment by NeoSunSoar** [comment]
> Personally I think the mention of being able to use with droppers is sufficient, if you start dropping in items en masse into the request system from a stash it will break the balance of the mod, not to mention this is going to fill your warehouses really fast.
> 
> If others feel like this is necessary, then fix the grammatical issues in the second sentence (no random uppercase words, "Worker" instead of "Worker's") also follow the guidelines of linking to buildings by using `{% include links/building.html key="warehouse" %}`

Hi,

Updated as requested. I checked and I didn't see a reference to a dropper on the Stash Wiki page. Is it mentioned elsewhere?  Thank you.

**Comment by Thodor12** [comment]
Same issues still apply, make "Workers" lowercase as this doesn't have to be titlecase.

Also you still added 1x more "Warehouse" in the text, please replace that with the above mentioned include template aswell.

**Comment by NeoSunSoar** [comment]
> Same issues still apply, make "Workers" lowercase as this doesn't have to be titlecase.
> 
> Also you still added 1x more "Warehouse" in the text, please replace that with the above mentioned include template aswell.

HI,

Removed second warehouse reference and lowercased workers references.  Thank you.

**Comment by Talyda** [comment]
I'm not sure this bit needs to be there?  (Is that what you meant Thodor?)
"This allows for the creation of automated farms outside of Minecolonies and cross compatibility with other mods that automate through machinery giving your workers access to the materials they need for the recipes you teach them. "

**Review by anonymous563 — APPROVED** [review]

**Comment by anonymous563** [comment]
> I'm not sure this bit needs to be there? (Is that what you meant Thodor?) "This allows for the creation of automated farms outside of Minecolonies and cross compatibility with other mods that automate through machinery giving your workers access to the materials they need for the recipes you teach them. "

I didn't even read the conversation and made the same changes as Shindria!

**Comment by Talyda** [comment]
=D Great minds think alike! So do ours!

**Comment by Talyda** [comment]
Oh, I do think it needs the bit about hoppers though - I think that was the main crux of their initial PR
Even if it just says " and can also accept input from hoppers"

**Comment by anonymous563** [comment]
Saying it works like a chest is sufficient since chests can accept hoppers.

**Comment by Talyda** [comment]
Ah! Fair!

**Comment by anonymous563** [comment]
If a player gets to this point without knowing that chests can interact with hoppers, then I'm not sure adding that info to the wiki will really do much to help them haha.

**Pull request merged**
