### PR TITLE
Kitteyschanges

### PR DESCRIPTION
**Pull request by d34thii**
Fixed issue #304: Updated the stats in `workerinfo.md` and added the missing jobs

Fixed Issue #305: Changed the worker primary/secondary stats for each `<worker>.md` to the ones used in-game

Fixed Issue #306: Added missing link to the Florist in `workerinfo.md`

Added possible fix for #302: Added the directory-link to the dyes and changed the filetype of `shingleslabthatched` to .json (Not 100% sure if that'll be the fix though)

### CODE REVIEW

**Comment by ravenbuilder934** [comment]
You added a lot of traits that are not shown in my game, like Focus, Adaptability, Athletics, Knowledge, Creativity, and Mana. I just have Strength, Charisma, Endurance, Intelligence, and Dexterity, and the traits before you changed them matched my game (except for the blacksmith, which the wiki showed as having Strength and Endurance instead of Dexterity and Strength). I'm not sure if this is just my version, though.

**Comment by Asherslab** [comment]
@ravenbuilder934 these stats are for 1.15.2

**Comment by ravenbuilder934** [comment]
> @ravenbuilder934 these stats are for 1.15.2

Oh, I'm playing on 1.12.2. Maybe we could add both stats to support the players on 1.12.2? (My friend told me a lot of people play 1.12.2 since it has more mods.)

**Comment by Asherslab** [comment]
@ravenbuilder934 our wiki is built for the latest version of the mod. we cannot maintain the wiki for multiple versions feasibly

**Comment by ravenbuilder934** [comment]
Okay. Could we maybe put a note on the main page then so 1.12.2 players don't get confused? I know I would be...

**Comment by Asherslab** [comment]
@d34thii mind adding a message on the front page about the wiki only covering the latest supported MC version?

**Comment by d34thii** [comment]
@Asherslab I can look into that.

**Pull request merged**
