### PR TITLE
Nether Mine Hut Update

### PR DESCRIPTION
**Pull request by Nikademus**
Closes #

## Changes proposed:
- Added Nether Mine Hut page & images
- Updated recipe page to include Nether Mine
- fixed missing cactusplank.png error on recipe page

Merge please :D

### CODE REVIEW

**Comment by Nikademus** [comment]
Not sure what's going on with buildinginfo.yml, all I added was the nethermine info but it's saying I added everything from the previous PR.

**Review by anonymous563 — APPROVED** [review]

**Comment by anonymous563** [comment]
To add more info, is there anything about the gear that they can use?

**Comment by Nikademus** [comment]
I figured the gear would be mentioned on worker page.

**Comment by anonymous563** [comment]
There's no mention of gear for the Nether Worker at all right now, though.

**Comment by Nikademus** [comment]
I guess I'll revise the worker pages next. :)  Should the worker equipment be mentioned on the hut page?  If so, I'll add something.

**Comment by anonymous563** [comment]
Fair point. It should go on the worker page for consistency.

**Comment by anonymous563** [comment]
Closed #794

**Pull request merged**
