### PR TITLE
Hut updates

### PR DESCRIPTION
**Pull request by Nikademus**
Closes #

## Changes proposed:
- Added pencil to hut gui
- fixed HTML formating for builder's page
- updated Shepherd's hut with new images and details.

Merge please :D

### CODE REVIEW

**Review by anonymous563 — APPROVED** [review]

**Comment by anonymous563** [comment]
There are some conflicts with source/buildings/builder.md. Can you resolve those?

**Review by anonymous563 — APPROVED** [review]

**Comment by Talyda** [comment]
I know you already closed this and put it through Ren, but I really think the hut GUI's need to show the whole GUI, not the cropped version like on the Builder's page 
Like on the Quarry page, I did the whole GUI
https://wiki.minecolonies.ldtteam.com/assets/images/gui/quarrygui1.png
Having a cropped version is actually going to confuse people, because they don't read far enough - they just see "Mine looks different to that"

(as a side note, I need to change "This is page two of the Quarry's GUI." to "This is the second tab" =P)

**Comment by Talyda** [comment]
If you would rather it this way, that's fine, but it needs to be consistent.

I can easily crop the ones I have been working on to match =)

**Comment by anonymous563** [comment]
No, I agree. I was just getting something in to start. I'll make an issue referencing this to update in the future.

**Comment by Talyda** [comment]
Oh! Okey doke!

**Pull request merged**
