### PR TITLE
adds Mineshaft information and updates Mine information

### PR DESCRIPTION
**Pull request by stolencatkarma**
There was no information on how to correctly make a mineshaft on the wiki. This should be enough information now for someone who wants to make a style pack.

This does however leave a hanging link to the mineshaft itself.

Closes #

## Changes proposed:
- 
-

### CODE REVIEW

**Comment by MotionlessTrain** [comment]
A mineshaft is not a building, so a link to a building page named "mineshaft" won't work
There are by the way more mine nodes than just a mineshaft. The minermainshaft is just the piece miners use to go vertical

**Comment by stolencatkarma** [comment]
So are you proposing i close this issue?

**Comment by MotionlessTrain** [comment]
I think the mineshafts could get their own section instead, together with the mine nodes, instead of putting them in the table of the building requirements

**Review by anonymous563 — CHANGES_REQUESTED** [review]
Rather than adding a hanging link, adjusting the info to refer to the needed tags in the tag tool would be better since the info is already on the tag tool page.

**Comment by stolencatkarma** [comment]
https://wiki.minecolonies.ldtteam.com/source/items/tagtool

In the tag tool its saying that those tags goto the mineshaft but they
actually go on the mine blueprint. Would me clarifying that on the tagtool
page work? I still think it needs to be clarified somewhere in the style
sheet the requirements for a mineshaft. (size, rotation, etc...)

cobble Mine Always 1 The block behind the top-most ladder at the start of
the mineshaft (traditionally cobblestone, but may be something else)
ladder Mine Always 1 The top-most ladder at the start of the mineshaft

**Comment by MotionlessTrain** [comment]
> Rather than adding a hanging link, adjusting the info to refer to the needed tags in the tag tool would be better since the info is already on the tag tool page.

The mineshafts don't use any tags.
The mine tags go on the mineshaft part of the building (that is, don't use the ladder tag on any other ladder in the mine building)

**Comment by stolencatkarma** [comment]
so two things are being referred to as the mine shaft. the ladder in the
mine hut and the decoration known as minermainshaft.

The fact that the minermainshaft needs to be a certain size and rotation
needs to go somewhere on the wiki for people who want to make a style pack.
It shouldn't be something that gets re-asked on discord over and over,

**Comment by MotionlessTrain** [comment]
> I think the mineshafts could get their own section instead, together with the mine nodes, instead of putting them in the table of the building requirements

Indeed. But as there are 8 mineshaft schematics in total, I think it deserves its own section on the schematics page of the wiki (as I mentioned earlier). Just like the decoration controller has its own section as well

**Comment by stolencatkarma** [comment]
So we can either edit
https://wiki.minecolonies.ldtteam.com/source/tutorials/schematics#how-to-create-custom-huts
or
https://wiki.minecolonies.ldtteam.com/source/items/tagtool

what's the decision?

**Comment by MotionlessTrain** [comment]
There are no tags involved with the mine shaft decorations, so tag tool page doesn't make sense.

Somewhere at the bottom of the schematics page is the best place, in my opinion

**Comment by anonymous563** [comment]
I agree with MotionlessTrain: the edits should be on the Schematics page, not the Tag Tool page. However, since a mine shaft is not a building, I will still oppose the addition of a hanging link.

**Comment by stolencatkarma** [comment]
no more hanging link and references the scan tool.

**Pull request merged**
