### PR TITLE
Changed a lot of building pages (details below)

### LINKED ISSUE #323: Forum links are different?
When I go to minecolonies.com and click on Forums (in the banner on the top of the page), it takes me [here.](https://www.reddit.com/r/Minecolonies/) But when I go to the wiki and do the same thing, it takes me [here.](https://forum.minecolonies.com/) They're both working forums, so I'm not sure which one is correct.

### LINKED ISSUE #324: Knight not in lists of workers
The Knight worker page doesn't show up on the dropdown menu or the list of workers on the wiki home.

### PR DESCRIPTION
**Pull request by ravenbuilder934**
I updated the Citizen Hut, Bakery, Blacksmith's Hut, Chicken Herder's Hut, Cowboy's Hut, Shepherd's Hut, Swine Herder's Hut, Composter's Hut, Fisherman's Hut, Farm & Field, Crusher's Hut, Deliveryman's Hut, Lumberjack's Hut, Flower Shop, Enchanter's Tower, Library, Hospital, Mine, Restaurant, Sawmill, and GUI pages. More to come.

I also closed #324, put a link to the wiki home on the 404 page, and closed #323 by adding a dropdown menu (hopefully-I'm not sure I did it right).

### CODE REVIEW

**Comment by lunadragnstar** [comment]
The sections on all the worker huts where we use the item.content is the default GUI information, you can change that file to update all the hut GUI information. (but allow for the first line change you made to state the hut. This way if the GUI is changed for any reason we only have 1 file to change, not all workers.

**Comment by lunadragnstar** [comment]
{% for item in site.data.gui.global %}
        <li><strong>{{ item.button }}:</strong> {{ item.content }}</li>
      {% endfor %}

**Comment by ravenbuilder934** [comment]
> The sections on all the worker huts where we use the item.content is the default GUI information, you can change that file to update all the hut GUI information. (but allow for the first line change you made to state the hut. This way if the GUI is changed for any reason we only have 1 file to change, not all workers.

Okay, I'll (try to) fix it.

**Comment by ravenbuilder934** [comment]
What is the GUI file called?

**Comment by ravenbuilder934** [comment]
Did I fix it? (I only updated the Bakery GUI so far.)

**Comment by lunadragnstar** [comment]
I invited you to our Insights discord so it is easier to discuss the Wiki changes

**Comment by ravenbuilder934** [comment]
@lunadragnstar Is the Insights discord text only or is it voice?

**Comment by lunadragnstar** [comment]
Just a discord server

**Comment by ravenbuilder934** [comment]
I changed it, does it work now?

**Comment by lunadragnstar** [comment]
Looks like the bakery is the only one showing correct

**Comment by ravenbuilder934** [comment]
I haven't updated the others yet, but will do it tomorrow

**Comment by ravenbuilder934** [comment]
Okay, I think I fixed the rest. I also added the Never button to the GUI page (for delivery priority).

**Comment by lunadragnstar** [comment]
Merged

**Pull request merged**
