### PR TITLE
Update schematics.mdoc

### PR DESCRIPTION
**Pull request by Talyda**
Adding new numbers for fishing pond size

[new numbers from discord discussion here](https://discord.com/channels/139070364159311872/1125094832143077456/1242033878122762270)

Closes #

## Changes proposed:
- 
-

### CODE REVIEW

**Review by Thodor12 — CHANGES_REQUESTED** [review]
Update the cases on the worker and building page as well, I didn't know this one was also there, but otherwise we still have conflicting info.

(To be honest we should probably remove this occurence since it's not mandatory)

**Comment by Talyda** [comment]
> Update the cases on the worker and building page as well, I didn't know this one was also there, but otherwise we still have conflicting info.
> 
> (To be honest we should probably remove this occurence since it's not mandatory)

No, it shouldn't be removed, cos schematics makers still need to know it

I also have no idea how to add to a PR to change the other pages, so please approve this one, and I will change the others separately later

**Comment by Thodor12** [comment]
@Talyda You can go and make changes to any extra files you want. But in the dialog where it tells you to commit, it'll ask you whether you want to make a new branch, or add the changes to an existing branch. You have to choose existing branch and select "Talyda:patch-5" (the branch you made this PR from)

**Comment by Thodor12** [comment]
I've changed this with https://github.com/ldtteam/MinecoloniesWiki/commit/63509d58e83831839ba42cd38ce186a221be02bb to further mitigate any issues with conflicting pond sizes (and potentially other common pieces of info later on)

**Comment by Talyda** [comment]
> choose existing branch and select "Talyda:patch-5" (the branch you made this PR from)

Ah! Okey dokey! Thanks Thodor!

**Pull request closed without merging**
