### PR TITLE
Fisher & Mine notes

### PR DESCRIPTION
**Pull request by Nikademus**
Closes #

## Changes proposed:
- Added note about ocean biome to Fisher Hut
- Added note about minimum Y levels to Mine

Merge please :D

### CODE REVIEW

**Comment by Talyda** [comment]
"It's recommended to always have your hut above Y=54 (1.16) or Y=44 (1.18)."
Where did that come from? I've never heard that before. You can build the mine at any Y level, you just have to upgrade it for it to work if you go lower

**Comment by MotionlessTrain** [comment]
> "It's recommended to always have your hut above Y=54 (1.16) or Y=44 (1.18)."
> Where did that come from? I've never heard that before. You can build the mine at any Y level, you just have to upgrade it for it to work if you go lower

A remark from Moobien iirc

**Comment by Nikademus** [comment]
Yep.  A few blocks above minimum for level 1 will prevent the error.  For most of the schematics, that's 4 blocks.

**Comment by Talyda** [comment]
Yeah, it's not anything I have ever heard =)
Even with 1.16, you can still start your mine at something like y11 and it's fine.  I just feel like that isn't a thing that has ever been recommended.  The first part of the comment absolutely is true, but that second part just isn't anything I have ever heard anyone say =)  In fact with underground colonies, it's impossible to follow

**Comment by Nikademus** [comment]
I'll change the wording.

**Review by anonymous563 — APPROVED** [review]

**Pull request merged**
